print("                  __ __   __")
print("                 (  |  ) /_/")
print("             __ (  >o<  )")
print("             \_\ (__|__)")
print(  )
print(  )
print("          _,-._")
print("         / \_/ \\")
print("         >-( )-<")
print("         \_/ \_/")
print("           '-'")
